#!/bin/bash



INTERFACES=""

USERNAME=""

PASSWORD=""

IP=""



usage () {

  echo "Usage $0 -u <username> -p <password> -i <IP address>"

  echo

  echo "Flags:"

  echo "  -u <username> Redfish Username"

  echo "  -p <password> Redfish password"

  echo "  -i <ip>       Redfish IP address"

  echo

  echo "Example:"

  echo "  $0 -u admin -p xxxx -i 1.2.3.4"

  exit 1

}





while getopts u:p:i: flag

do

  case "${flag}" in

    u)

      USERNAME=$OPTARG

      ;;

    p)

      PASSWORD=$OPTARG

      ;;

    i)

      IP=$OPTARG

      ;;

    *)

      usage

      ;;

  esac

done



if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ] || [ -z "$IP" ]; then

  usage

fi



SERIALNUMBER=$(curl -k -s https://$USERNAME:$PASSWORD@$IP/redfish/v1/Chassis | grep odata.id | awk '{ print $2 }' | awk -F'/' '{ print $5 }' | egrep -v '^$|1"' | sed 's/"//')

INTERFACES=$(curl -k -s https://$USERNAME:$PASSWORD@$IP/redfish/v1/Chassis/$SERIALNUMBER/NetworkAdapters/ | grep odata.id | awk '{ print $2 }' | sed 's/"//g')



echo

echo "Redfish URL: redfish-virtualmedia+https://$IP/redfish/v1/Systems/$SERIALNUMBER"

echo

echo "MAC Addresses:"



for foo in $INTERFACES

do

  curl -k -s https://$USERNAME:$PASSWORD@$IP$foo| grep BaseMac | awk '{ print $2 }' | sed 's|",||g' | sed 's|"|  |'

done
 
